--- #YAML:1.0
name:                MIME-tools
version:             5.421
abstract:            Tools to manipulate MIME messages
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Path:                    1
    File::Spec:                    0.6
    File::Temp:                    0.12
    IO::Stringy:                   2.11
    Mail::Field:                   1.05
    Mail::Header:                  1.01
    Mail::Internet:                1.0203
    MIME::Base64:                  2.2
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Eryq <eryq@zeegee.com>, David F. Skoll <dfs@roaringpenguin.com>, Dave O'Neill <dmo@roaringpenguin.com>
