--- 
abstract: Tools to manipulate MIME messages
author: Eryq <eryq@zeegee.com>, David F. Skoll <dfs@roaringpenguin.com>, Dave O'Neill <dmo@roaringpenguin.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MIME-tools
no_index: 
  directory: 
    - inc
    - t
recommends: 
  MIME::Base64: 3.03
requires: 
  File::Path: 1
  File::Spec: 0.6
  File::Temp: 0.18
  IO::File: 0
  IO::Handle: 0
  IO::Stringy: 2.11
  MIME::Base64: 2.2
  Mail::Field: 1.05
  Mail::Header: 1.01
  Mail::Internet: 1.0203
  perl: 5.8.0
version: 5.426
