=head1 NAME

MIME::Tools::config - configuring MIME-tools


=head1 SYNOPSIS

This is part of the MIME-tools documentation.
See L<MIME::Tools> for the full table of contents.


=head1 DESCRIPTION

This document describes how the toolkit can be globally
configured.


=head1 CONFIGURING

=over

=item debugging

Turn debugging on or off.
Default is false (off).

     MIME::Tools->debugging(1);

See L<MIME::Tools::diag> to learn about how (and when)
debug messages are output.


=item quiet

Turn the reporting of warning/error messages on or off.
Default is false, meaning that these message are not silenced.

     MIME::Tools->quiet(1);

See L<MIME::Tools::diag> to learn about how (and when)
warnings are output.


=item version

Return the toolkit version.

     print MIME::Tools->version, "\n";

=back




=head1 SEE ALSO

See L<MIME::Tools/SYNOPSIS> for the full table of contents.

