#!/usr/bin/perl -w

use strict;
use FindBin qw($Bin);
use lib "$Bin/../../lib";
use MIME::Entity;

my $ent = MIME::Entity->build(Subject => "Hello",
			      Data => "This is a test of signatures.\n");
$ent->sign(Attach=>1,
	   Charset=>"UTF-8",
	   Signature=>"Eryq");
$ent->print;
