


=head1 NAME

MIME-tools - modules for parsing (and creating!) MIME entities



=head1 SYNOPSIS

For coding examples, see the MIME::Tools module.
This manpage is for installers.



=head1 CONTENTS


=head2 Modules in this toolkit

    Module       DSLI   Description                                  Info
    ----------   ----   ------------------------------------------   ----
    MIME::
    ::Body       adpO   Abstract message holder (file, scalar, etc.) ERYQ
    ::Decoder    bdpO   OO interface for decoding MIME messages      ERYQ
    ::Entity     bdpO   An extracted and decoded MIME entity         ERYQ
    ::Field::*   bdpO   Mail::Field subclasses for parsing fields    ERYQ
    ::Head       bdpO   A parsed MIME header (Mail::Header subclass) ERYQ
    ::Parser     bdpO   Parses streams to create MIME entities       ERYQ
    ::ParserBase bdpO   For building your own MIME parser            ERYQ
    ::ToolUtils  bdpO   Utilities for the MIME-tools kit             ERYQ
    ::Tools      bdpO   For configuring the MIME-tools library       ERYQ
    ::Words      bdpO   Decode encoded words in MIME headers         ERYQ
    
    ::IO         ****   DEPRECATED; now done via IO:: modules        ERYQ
    ::Latin1     ****   DEPRECATED; may be moved to Text::           ERYQ

=head2 Programs in this toolkit

    mimeabuse   - try hard to break MIME parsing
    mimedump    - dump out summary of the contents of a parsed MIME message
    mimeencode  - encode a file
    mimeexplode - explode one or more MIME messages
    mimeprint   - parse a MIME stream, and print the parsed entity
    mimesend    - send files via MIME mail, from the command line
    mimetour    - tour the possible encodings

=head2 Layout of the distribution

    ./lib/MIME/         the MIME-tools classes
    ./Makefile.PL       the input to MakeMaker
    ./COPYING           terms and conditions for copying/using the software
    ./README            this file
    ./docs/             HTMLized documentation
    ./etc/              convenient copies of other modules you may need
    ./examples          sample executables
    ./t/*.t             the "make test" scripts
    ./testin/           files you can use for testing (as in "make test")
    ./testout/          the output of "make test"




=head1 REQUIREMENTS

You'll need B<Perl5.002> or better, but you I<should> get 5.004 as
soon as possible... sorry, but it's the first release I know of with 
a non-broken FileHandle->new_tmpfile method.  It's extremely worth 
upgrading to if you're using MIME-tools.

You'll also need to obtain and install the following kits from the CPAN:

=over 4

=item IO-stringy 

This provides us with filehandle-like interfaces to scalars,
and the ability to "wrap" foreign filehandles.

=item MIME-Base64 (2.04 or higher)

This kit contains MIME::Base64 and MIME::QuotedPrint, which perform the 
low-level MIME decoding.  Get these from B<Gisle Aas'> author directory. 
They are also reported to be in the LWP distribution.

=item MailTools (1.11 or higher)

This is B<Graham Barr's> revamped set of Mail:: modules.
Many of them are now superclasses of the MIME:: modules, and
perform the core functionality of manipulating headers and fields.

=back


=head1 INSTALLATION

Pretty simple:

    1. Gunzip and de-tar the distribution, and cd to the top level.
    2. Type:      perl Makefile.PL
    3. Type:      make                    # this step is optional
    4. Type:      make test               # this step is optional
    5. Type:      make install

Other interesting targets in the Makefile are:

    make config     # to check if the Makefile is up-to-date
    make clean      # delete local temp files (Makefile gets renamed)
    make realclean  # delete derived files (including ./blib)

If you're installing this as a replacment for MIME-parser 1.x or earlier,
I<please> read the L<"Compatibility"> notes.



=head1 TERMS AND CONDITIONS

Copyright (c) 1996 by Eryq.  All rights reserved.  This program is free
software; you can redistribute it and/or modify it under the same terms as
Perl itself.  See the COPYING file in the distribution for details.



=head1 AUTHOR

MIME-tools was created by:

    ___  _ _ _   _  ___ _     
   / _ \| '_| | | |/ _ ' /    Eryq (President, Zero G Inc.)
  |  __/| | | |_| | |_| |     http://www.zeegee.com/
   \___||_|  \__, |\__, |__   eryq@zeegee.com
             |___/    |___/

For full credits, see the MIME::Tools module.




